/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menu.analise_sist_elab_vinho_e_derivados.elaboracao.fermentacao;

import java.awt.Dimension;
import javax.swing.table.DefaultTableModel;
import static menu.analise_sist_elab_vinho_e_derivados.elaboracao.fermentacao.VisualizaCadastroFermentacao.aux;
import static menu.analise_sist_elab_vinho_e_derivados.elaboracao.fermentacao.VisualizaCadastroFermentacao.jtCodigo;
import static menu.analise_sist_elab_vinho_e_derivados.elaboracao.fermentacao.VisualizaCadastroFermentacao.jtData;
import static menu.analise_sist_elab_vinho_e_derivados.elaboracao.fermentacao.VisualizaCadastroFermentacao.jtDescricao;
import static menu.analise_sist_elab_vinho_e_derivados.elaboracao.fermentacao.VisualizaCadastroFermentacao.jtNumeroTanque;
import static menu.analise_sist_elab_vinho_e_derivados.elaboracao.fermentacao.VisualizaCadastroFermentacao.jtOrigem;
import static menu.analise_sist_elab_vinho_e_derivados.elaboracao.fermentacao.VisualizaCadastroFermentacao.jtVolume;


public class TelaListagemFermentacao extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaListagemFermentacao
     */
    public TelaListagemFermentacao() {
        initComponents();
        Arquivo.leitura(jTable1);
    }

    public void setPosicaoCentro() {
        Dimension d = this.getDesktopPane().getSize();
        System.out.println(d.width);
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2); 
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btNovo = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btRemove = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonVisualizar = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Listagem de Cadastros de Fermentação");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel1.setText("Código");

        jButton1.setText("Pesquisar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btNovo.setText("Novo");
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });

        jButton3.setText("Editar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        btRemove.setText("Remover");
        btRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoveActionPerformed(evt);
            }
        });

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Descrição", "Data de enchimento", "Nº Tanque de Fermentação", "Volume", "Origem"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButtonVisualizar.setText("Visualizar");
        jButtonVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVisualizarActionPerformed(evt);
            }
        });

        jButton7.setText("Limpar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btNovo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonVisualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btRemove)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btNovo)
                    .addComponent(jButton3)
                    .addComponent(btRemove)
                    .addComponent(jButtonVisualizar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7))
        );

        setBounds(0, 0, 709, 563);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVisualizarActionPerformed
        visualizaLinha();   
    }//GEN-LAST:event_jButtonVisualizarActionPerformed

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        TelaCadastroFermentacao telaCadastroFermentacao = new TelaCadastroFermentacao();
        telaCadastroFermentacao.setVisible(true);
        
    }//GEN-LAST:event_btNovoActionPerformed

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        Arquivo.salvar(jTable1);
        
        
    }//GEN-LAST:event_formInternalFrameClosing

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        editaLinha();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoveActionPerformed
        // botao remover
        removeLinha();
        
    }//GEN-LAST:event_btRemoveActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       // botao pesquisar
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btNovo;
    private javax.swing.JButton btRemove;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButtonVisualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables


    private void visualizaLinha()
    {
        int indexSelectedRow;
        indexSelectedRow = jTable1.getSelectedRow();
        VisualizaCadastroFermentacao.aux = indexSelectedRow;
        if (indexSelectedRow != -1) {
        VisualizaCadastroFermentacao vcf1 = new VisualizaCadastroFermentacao();
        vcf1.setVisible(true);
        
        VisualizaCadastroFermentacao.jtCodigo.setEnabled(false);
        VisualizaCadastroFermentacao.jtDescricao.setEnabled(false);
        VisualizaCadastroFermentacao.jtData.setEnabled(false);
        VisualizaCadastroFermentacao.jtVolume.setEnabled(false);
        VisualizaCadastroFermentacao.jtNumeroTanque.setEnabled(false);
        VisualizaCadastroFermentacao.jtOrigem.setEnabled(false);
        VisualizaCadastroFermentacao.btSalvar.setVisible(false);
        VisualizaCadastroFermentacao.btCancelar.setVisible(false);
        
       
        
        VisualizaCadastroFermentacao.jtCodigo.setText(jTable1.getValueAt(indexSelectedRow, 0).toString());
        VisualizaCadastroFermentacao.jtDescricao.setText(jTable1.getValueAt(indexSelectedRow, 1).toString());
        VisualizaCadastroFermentacao.jtData.setText(jTable1.getValueAt(indexSelectedRow, 2).toString());
        VisualizaCadastroFermentacao.jtNumeroTanque.setText(jTable1.getValueAt(indexSelectedRow, 3).toString());
        VisualizaCadastroFermentacao.jtVolume.setText(jTable1.getValueAt(indexSelectedRow, 4).toString());
        VisualizaCadastroFermentacao.jtOrigem.setText(jTable1.getValueAt(indexSelectedRow, 5).toString());
        }
        
        
        
    }
    private void editaLinha()
    {
        int indexSelectedRow;
        indexSelectedRow = jTable1.getSelectedRow();
        VisualizaCadastroFermentacao.aux = indexSelectedRow;
        
        if (indexSelectedRow != -1) {
        VisualizaCadastroFermentacao vcf1 = new VisualizaCadastroFermentacao();
        vcf1.setVisible(true);
        
        VisualizaCadastroFermentacao.jtCodigo.setEnabled(true);
        VisualizaCadastroFermentacao.jtDescricao.setEnabled(true);
        VisualizaCadastroFermentacao.jtData.setEnabled(true);
        VisualizaCadastroFermentacao.jtVolume.setEnabled(true);
        VisualizaCadastroFermentacao.jtNumeroTanque.setEnabled(true);
        VisualizaCadastroFermentacao.jtOrigem.setEnabled(true);
        VisualizaCadastroFermentacao.jButton1.setVisible(false);
        VisualizaCadastroFermentacao.btSalvar.setVisible(true);
        VisualizaCadastroFermentacao.btCancelar.setVisible(true);
        
       
        
        VisualizaCadastroFermentacao.jtCodigo.setText(jTable1.getValueAt(indexSelectedRow, 0).toString());
        VisualizaCadastroFermentacao.jtDescricao.setText(jTable1.getValueAt(indexSelectedRow, 1).toString());
        VisualizaCadastroFermentacao.jtData.setText(jTable1.getValueAt(indexSelectedRow, 2).toString());
        VisualizaCadastroFermentacao.jtNumeroTanque.setText(jTable1.getValueAt(indexSelectedRow, 3).toString());
        VisualizaCadastroFermentacao.jtVolume.setText(jTable1.getValueAt(indexSelectedRow, 4).toString());
        VisualizaCadastroFermentacao.jtOrigem.setText(jTable1.getValueAt(indexSelectedRow, 5).toString());
        }
    }
    private void removeLinha()
    {
        int indexSelectedRow;
        indexSelectedRow = jTable1.getSelectedRow();
        System.out.println(indexSelectedRow);
        
        if (indexSelectedRow != -1) {
            DefaultTableModel dtmDados = (DefaultTableModel)jTable1.getModel();
            dtmDados.removeRow(indexSelectedRow);
        }
    }
    
    
}
